# Generated by Django 5.1.1 on 2024-09-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0002_meetup_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="image",
            field=models.ImageField(default="default", upload_to="images"),
            preserve_default=False,
        ),
    ]
