# Generated by Django 5.1.1 on 2024-09-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0004_location_alter_meetup_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetup",
            name="address",
        ),
    ]
