# Generated by Django 5.1.1 on 2024-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0007_remove_meetup_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
