# Generated by Django 5.1.1 on 2024-09-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0011_remove_location_address_location_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="stree_address",
            new_name="street_address",
        ),
    ]
